language: objective-c
osx_image: xcode9
branches:
  only:
    - master
before_install:
  - gem install xcpretty
script:
- set -o pipefail
- xcodebuild -project Example/YLTCPBroadcasterSample.xcodeproj -scheme YLTCPBroadcasterSampleTests -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES test | xcpretty -c
